### ISSUE TITLE
lrange before llen causes an incorrect key type error

### ISSUE THREAD

**Issue by skaufman-socialflow** [jlavallee/Test-Mock-Redis#20]
The lrange code as it stands makes perl auto-vivify an arrayref, which makes _is_list fail later.
https://github.com/jlavallee/Test-Mock-Redis/blob/be9160da261d1999793e8f4226d55799bcbd7e41/lib/Test/Mock/Redis.pm#L466

**Comment by valcomm** [comment]
I think this one is fixed in 0.22

**Comment by jlavallee** [comment]
Thanks!
